# Generated by Django 4.2.2 on 2023-06-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistant",
            name="id_card_number",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
