# Generated by Django 4.2.2 on 2023-06-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_assistant_bio_alter_assistant_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistant",
            name="passport",
            field=models.URLField(null=True),
        ),
    ]
