# Generated by Django 4.2.3 on 2023-07-07 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='time_created',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
