# Generated by Django 4.2.3 on 2023-07-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_otp_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='time_created',
            field=models.TimeField(auto_now=True),
        ),
    ]
