# Generated by Django 4.2.3 on 2023-09-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_otp_time_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistant',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='assistant',
            name='disability',
        ),
        migrations.RemoveField(
            model_name='assistant',
            name='height',
        ),
        migrations.AddField(
            model_name='assistant',
            name='linked_in',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='assistant',
            name='professional_headline',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='assistant',
            name='resume',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='assistant',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
